version: 2

project_name: nullify

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/cli
    binary: nullify
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X 'github.com/nullify-platform/logger/pkg/logger.Version={{ .Version }}'
      - -X 'github.com/nullify-platform/cli/internal/api.Version={{ .Version }}'
      - -X 'github.com/nullify-platform/cli/cmd/cli/cmd.buildCommit={{ .Commit }}'
      - -X 'github.com/nullify-platform/cli/cmd/cli/cmd.buildDate={{ .Date }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "nullify_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

brews:
  - name: nullify
    repository:
      owner: Nullify-Platform
      name: homebrew-tap
    homepage: "https://github.com/Nullify-Platform/cli"
    description: "Nullify CLI - autonomous AI workforce for product security"
    install: |
      bin.install "nullify"

release:
  github:
    owner: Nullify-Platform
    name: cli
  draft: false
  prerelease: auto
