// Code generated by scripts/generate/main.go. DO NOT EDIT.
package commands

import (
	"net/url"
	"os"

	"github.com/nullify-platform/cli/internal/api"
	"github.com/nullify-platform/cli/internal/output"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func RegisterDastCommands(parent *cobra.Command, getClient func() *api.Client) {
	serviceCmd := &cobra.Command{
		Use:   "dast",
		Short: "Dast commands",
	}
	parent.AddCommand(serviceCmd)

	{
		cmd := &cobra.Command{
			Use:   "list-config",
			Short: "Get BugHunt Config",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastBughuntConfig(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "update-config",
			Short: "Put BugHunt Config",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.UpdateDastBughuntConfig(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-findings",
			Short: "Get BugHunt Findings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastBughuntFindings(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-findings",
			Short: "Get BugHunt Finding",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.GetDastBughuntFindingsFindingId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "patch-allowlist",
			Short: "Allowlist BugHunt Finding",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.PatchDastBughuntFindingsFindingIdAllowlist(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-events",
			Short: "Get BugHunt Finding Events",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListDastBughuntFindingsFindingIdEvents(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-triage",
			Short: "Get Bug Hunt Finding Triage",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListDastBughuntFindingsFindingIdTriage(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-scans",
			Short: "Get BugHunt Scans",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastBughuntScans(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-scans",
			Short: "Start BugHunt Scan",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastBughuntScans(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-scans",
			Short: "Get BugHunt Scan",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.GetDastBughuntScansScanId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-findings",
			Short: "Get BugHunt Scan Findings",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastBughuntScansScanIdFindings(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-logs",
			Short: "Get BugHunt Sub-Agent Network Log",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastBughuntScansScanIdLogs(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-stop",
			Short: "Stop BugHunt Scan",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.CreateDastBughuntScansScanIdStop(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-schedule",
			Short: "Post Bug Hunt Schedule",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastBughuntSchedule(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "delete-schedule",
			Short: "Delete Bug Hunt Schedule",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.DeleteDastBughuntSchedule(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-schedule",
			Short: "Get Bug Hunt Schedule",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastBughuntSchedule(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "patch-schedule",
			Short: "Patch Bug Hunt Schedule",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.PatchDastBughuntSchedule(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-credentials",
			Short: "Create Credential",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastCredentials(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-credentials",
			Short: "Get All Credentials",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastCredentials(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "delete-credentials",
			Short: "Delete Credential",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("credentialId", args[0])
				}
				result, err := client.DeleteDastCredentialsCredentialId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-credentials",
			Short: "Get Credential",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("credentialId", args[0])
				}
				result, err := client.GetDastCredentialsCredentialId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "update-credentials",
			Short: "Update Credential",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("credentialId", args[0])
				}
				result, err := client.UpdateDastCredentialsCredentialId(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-validate",
			Short: "Validate Credential",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("credentialId", args[0])
				}
				result, err := client.CreateDastCredentialsCredentialIdValidate(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-start",
			Short: "Start AWS Integration Scan",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastIntegrationAwsScanStart(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-status",
			Short: "Get AWS Integration Scan Status",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastIntegrationAwsScanStatus(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		cmd.Flags().String("scanId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-schedule",
			Short: "Get AWS Integration Schedule",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastIntegrationAwsSchedule(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-schedule",
			Short: "Create/Update AWS Integration Schedule",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastIntegrationAwsSchedule(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "delete-schedule",
			Short: "Delete AWS Integration Schedule",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.DeleteDastIntegrationAwsSchedule(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-settings",
			Short: "Get AWS Integration Settings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastIntegrationAwsSettings(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-settings",
			Short: "Upsert AWS Integration Settings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastIntegrationAwsSettings(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-validate-role",
			Short: "Validate AWS Role Assumption",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastIntegrationAwsValidateRole(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-cloud-accounts",
			Short: "Get Asset Inventory Cloud Accounts",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastInventoryCloudAccounts(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("nextToken", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-endpoints",
			Short: "Create Asset Inventory Endpoints",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastInventoryEndpoints(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-endpoints",
			Short: "Get Asset Inventory Endpoints",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastInventoryEndpoints(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("nextToken", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-endpoints-by-host",
			Short: "Get Asset Inventory Endpoints by Host",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastInventoryEndpointsByHost(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("hostId", "", "")
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-hosts",
			Short: "Create Asset Inventory Hosts",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastInventoryHosts(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-hosts",
			Short: "Get Asset Inventory Hosts",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastInventoryHosts(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("includeArtifacts", "", "")
		cmd.Flags().String("nextToken", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-hosts-with-endpoints",
			Short: "Get Asset Inventory Hosts with Endpoints",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastInventoryHostsWithEndpoints(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("nextToken", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-triage",
			Short: "Get Asset Inventory Triage",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastInventoryTriage(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		cmd.Flags().String("repo_name", "", "")
		cmd.Flags().String("api_path", "", "")
		cmd.Flags().String("host_name", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-applications",
			Short: "Create Application",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastPentestApplications(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-applications",
			Short: "Get Pentest App Configs",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastPentestApplications(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("nextToken", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "update-applications",
			Short: "Update Application",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("applicationId", args[0])
				}
				result, err := client.UpdateDastPentestApplicationsApplicationId(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-applications",
			Short: "Get Pentest App Config",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("applicationId", args[0])
				}
				result, err := client.GetDastPentestApplicationsApplicationId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "delete-applications",
			Short: "Delete Pentest App Config",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("applicationId", args[0])
				}
				result, err := client.DeleteDastPentestApplicationsApplicationId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-findings",
			Short: "Get Pentest Findings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastPentestFindings(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("nextToken", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("scanId", "", "")
		cmd.Flags().String("priorityLabel", "", "")
		cmd.Flags().String("isFalsePositive", "", "")
		cmd.Flags().String("isLatest", "", "")
		cmd.Flags().String("isAllowlisted", "", "")
		cmd.Flags().String("isResolved", "", "")
		cmd.Flags().String("sortBy", "", "")
		cmd.Flags().String("sort", "", "")
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-findings",
			Short: "Get Pentest Finding",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.GetDastPentestFindingsFindingId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-allowlist",
			Short: "Allowlist Pentest Finding",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.CreateDastPentestFindingsFindingIdAllowlist(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-events",
			Short: "Get Pentest Finding Events",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListDastPentestFindingsFindingIdEvents(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-full",
			Short: "Get Pentest Finding Full",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListDastPentestFindingsFindingIdFull(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-ticket",
			Short: "Create Jira Ticket for Pentest Finding",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.CreateDastPentestFindingsFindingIdTicket(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-triage",
			Short: "Get Pentest Finding Full",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListDastPentestFindingsFindingIdTriage(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-scans",
			Short: "Get Pentest Scans",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastPentestScans(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("nextToken", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-external",
			Short: "Create new scan from an external DAST scanner",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastPentestScansExternal(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "patch-external",
			Short: "Update External Scan",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.PatchDastPentestScansExternalScanId(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-scans",
			Short: "Get Pentest Scan",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.GetDastPentestScansScanId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-findings",
			Short: "Get Pentest Scan Findings",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastPentestScansScanIdFindings(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-hypotheses",
			Short: "Get Auth Matrix Hypotheses",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastPentestScansScanIdHypotheses(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-logs",
			Short: "Get Sub-Agent Network Log",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastPentestScansScanIdLogs(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-report",
			Short: "Get Pentest Scan Report",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastPentestScansScanIdReport(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-download",
			Short: "Get Pentest Scan Report Download URL",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastPentestScansScanIdReportDownload(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-pdf",
			Short: "Get Pentest Scan External Report PDF",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastPentestScansScanIdReportExternalPdf(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-pdf",
			Short: "Get Pentest Scan Report PDF",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.ListDastPentestScansScanIdReportPdf(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-stop",
			Short: "Stop Pentest Scan",
			Args: cobra.MaximumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				if len(args) > 0 {
					params.Set("scanId", args[0])
				}
				result, err := client.CreateDastPentestScansScanIdStop(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-start",
			Short: "Start Pentest Scan from Application",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateDastPentestStart(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-last",
			Short: "Get Pentest Last Scan Status",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListDastScansStatusLast(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azureOrganizationId", "", "The Azure organization ID")
		cmd.Flags().String("bitbucketWorkspaceId", "", "The Bitbucket workspace ID")
		cmd.Flags().String("githubOwnerId", "", "The Github owner ID")
		cmd.Flags().String("gitlabGroupId", "", "The GitLab group ID")
		cmd.Flags().String("installationId", "", "The Nullify installation ID")
		cmd.Flags().String("azureRepositoryId", "", "")
		cmd.Flags().String("githubRepositoryId", "", "")
		cmd.Flags().String("githubTeamId", "", "")
		cmd.Flags().String("bitbucketRepositoryId", "", "")
		serviceCmd.AddCommand(cmd)
	}

}
