// Code generated by scripts/generate/main.go. DO NOT EDIT.
package commands

import (
	"net/url"

	"github.com/nullify-platform/cli/internal/api"
	"github.com/nullify-platform/cli/internal/output"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func RegisterInfrastructureCommands(parent *cobra.Command, getClient func() *api.Client) {
	serviceCmd := &cobra.Command{
		Use:   "infrastructure",
		Short: "Infrastructure Graphs",
	}
	parent.AddCommand(serviceCmd)

	{
		cmd := &cobra.Command{
			Use:   "list-graphs",
			Short: "List Infrastructure Graphs",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.ListInfrastructureGraphs(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-info",
			Short: "Get Infrastructure Graph Info",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.ListInfrastructureGraphsInfo(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-summary",
			Short: "Get Infrastructure Graph Summary",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.ListInfrastructureGraphsSummary(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-graphs <accountId>",
			Short: "Get Infrastructure Graph",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("accountId", args[0])
				}
				result, err := client.GetInfrastructureGraphsAccountId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-download <accountId>",
			Short: "Get Infrastructure Graph Download URL",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("accountId", args[0])
				}
				result, err := client.ListInfrastructureGraphsAccountIdDownload(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-graphs-versions <accountId>",
			Short: "List Infrastructure Graph Versions",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("accountId", args[0])
				}
				result, err := client.ListInfrastructureGraphsAccountIdVersions(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-graphs-versions-2 <accountId> <version>",
			Short: "Get Infrastructure Graph Version",
			Args:  cobra.ExactArgs(2),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("accountId", args[0])
				}
				if len(args) > 1 {
					params.Set("version", args[1])
				}
				result, err := client.ListInfrastructureGraphsAccountIdVersionsVersion(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

}
