// Code generated by scripts/generate/main.go. DO NOT EDIT.
package commands

import (
	"net/url"
	"os"

	"github.com/nullify-platform/cli/internal/api"
	"github.com/nullify-platform/cli/internal/output"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func RegisterScpmCommands(parent *cobra.Command, getClient func() *api.Client) {
	serviceCmd := &cobra.Command{
		Use:   "scpm",
		Short: "SaaS Security Posture Management (SCPM)",
	}
	parent.AddCommand(serviceCmd)

	{
		cmd := &cobra.Command{
			Use:   "create-containers-analyze",
			Short: "Request malware analysis for an OCI container image",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateScpmContainersAnalyze(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-dependencies",
			Short: "Get CI/CD Dependencies",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.ListScpmDependencies(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("name", "", "Filter by dependency name (e.g., actions/checkout, tj-actions/changed-files)")
		cmd.Flags().String("version", "", "Filter by version reference (requires name)")
		cmd.Flags().String("platform", "", "Filter by CI/CD platform (github-actions, gitlab-ci, azure-pipelines)")
		cmd.Flags().String("pinned", "", "Filter by pinned status")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-dependencies-analyze",
			Short: "Request malware analysis for a dependency",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateScpmDependenciesAnalyze(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-batch",
			Short: "Batch query vulnerabilities + malware verdict for dependencies",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					params.Set(f.Name, f.Value.String())
				})
				result, err := client.CreateScpmDependenciesQueryBatch(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-events",
			Short: "Get SCPM Events",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.ListScpmEvents(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-findings",
			Short: "Get SCPM Findings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"next-token": "nextToken",
					"priority-label": "priorityLabel",
					"file-owner-name": "fileOwnerName",
					"has-pull-request": "hasPullRequest",
					"repository-ids": "repositoryIds",
					"is-resolved": "isResolved",
					"is-fixed": "isFixed",
					"is-false-positive": "isFalsePositive",
					"is-allowlisted": "isAllowlisted",
					"is-archived": "isArchived",
					"sort-by": "sortBy",
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.ListScpmFindings(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("next-token", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("priority-label", "", "")
		cmd.Flags().String("severity", "", "")
		cmd.Flags().String("file-owner-name", "", "")
		cmd.Flags().String("has-pull-request", "", "")
		cmd.Flags().String("branch", "", "")
		cmd.Flags().String("workflow", "", "")
		cmd.Flags().String("repository-ids", "", "if not provided, all repositories will be included")
		cmd.Flags().String("is-resolved", "", "combination of isFixed, isFalsePositive, isAllowlisted and isArchived")
		cmd.Flags().String("is-fixed", "", "")
		cmd.Flags().String("is-false-positive", "", "")
		cmd.Flags().String("is-allowlisted", "", "")
		cmd.Flags().String("is-archived", "", "")
		cmd.Flags().String("sort-by", "", "")
		cmd.Flags().String("sort", "", "")
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-allowlist",
			Short: "Allowlist Batch of SCPM Findings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.CreateScpmFindingsAllowlist(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-detailed",
			Short: "Get Findings Detailed",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"next-token": "nextToken",
					"priority-label": "priorityLabel",
					"file-owner-name": "fileOwnerName",
					"has-pull-request": "hasPullRequest",
					"is-resolved": "isResolved",
					"is-fixed": "isFixed",
					"is-false-positive": "isFalsePositive",
					"is-allowlisted": "isAllowlisted",
					"is-archived": "isArchived",
					"sort-by": "sortBy",
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.ListScpmFindingsDetailed(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("next-token", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("priority-label", "", "")
		cmd.Flags().String("severity", "", "")
		cmd.Flags().String("file-owner-name", "", "")
		cmd.Flags().String("has-pull-request", "", "")
		cmd.Flags().String("branch", "", "")
		cmd.Flags().String("workflow", "", "")
		cmd.Flags().String("is-resolved", "", "combination of isFixed, isFalsePositive, isAllowlisted and isArchived")
		cmd.Flags().String("is-fixed", "", "")
		cmd.Flags().String("is-false-positive", "", "")
		cmd.Flags().String("is-allowlisted", "", "")
		cmd.Flags().String("is-archived", "", "")
		cmd.Flags().String("sort-by", "", "")
		cmd.Flags().String("sort", "", "")
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "list-preview",
			Short: "Get SCPM Findings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"next-token": "nextToken",
					"priority-label": "priorityLabel",
					"file-owner-name": "fileOwnerName",
					"has-pull-request": "hasPullRequest",
					"repository-ids": "repositoryIds",
					"is-resolved": "isResolved",
					"is-fixed": "isFixed",
					"is-false-positive": "isFalsePositive",
					"is-allowlisted": "isAllowlisted",
					"is-archived": "isArchived",
					"sort-by": "sortBy",
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.ListScpmFindingsPreview(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("next-token", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("priority-label", "", "")
		cmd.Flags().String("severity", "", "")
		cmd.Flags().String("file-owner-name", "", "")
		cmd.Flags().String("has-pull-request", "", "")
		cmd.Flags().String("branch", "", "")
		cmd.Flags().String("workflow", "", "")
		cmd.Flags().String("repository-ids", "", "if not provided, all repositories will be included")
		cmd.Flags().String("is-resolved", "", "combination of isFixed, isFalsePositive, isAllowlisted and isArchived")
		cmd.Flags().String("is-fixed", "", "")
		cmd.Flags().String("is-false-positive", "", "")
		cmd.Flags().String("is-allowlisted", "", "")
		cmd.Flags().String("is-archived", "", "")
		cmd.Flags().String("sort-by", "", "")
		cmd.Flags().String("sort", "", "")
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-retriage",
			Short: "Retriage Findings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.CreateScpmFindingsRetriage(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-upload",
			Short: "Get Presigned URL to Upload SCPM Findings",
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				result, err := client.CreateScpmFindingsUpload(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "patch-findings <findingId>",
			Short: "Update Finding",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.PatchScpmFindingsFindingId(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-findings <findingId>",
			Short: "Get Finding",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.GetScpmFindingsFindingId(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-allowlist-by-id <findingId>",
			Short: "Allowlist Finding",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.CreateScpmFindingsFindingIdAllowlist(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-activity <findingId>",
			Short: "Get SCPM Finding Autofix Activity",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"since-id": "since_id",
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListScpmFindingsFindingIdAutofixActivity(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("since-id", "", "")
		cmd.Flags().String("limit", "", "")
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-cache-by-id <findingId>",
			Short: "Cache Autofix",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.CreateScpmFindingsFindingIdAutofixCache(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-create_pr-by-id <findingId>",
			Short: "Create Pull Request from Cached Fix",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.CreateScpmFindingsFindingIdAutofixCacheCreatePr(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-diff <findingId>",
			Short: "Get SCPM Finding Autofix Diff",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListScpmFindingsFindingIdAutofixCacheDiff(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-fix-by-id <findingId>",
			Short: "Autofix Finding",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.CreateScpmFindingsFindingIdAutofixFix(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-state <findingId>",
			Short: "Get SCPM Finding Autofix State",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListScpmFindingsFindingIdAutofixState(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-status <findingId>",
			Short: "Get SCPM Finding Autofix Status",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListScpmFindingsFindingIdAutofixStatus(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-events <findingId>",
			Short: "Get Finding Events",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListScpmFindingsFindingIdEvents(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "get-triage <findingId>",
			Short: "Get Triaged Finding",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.ListScpmFindingsFindingIdTriage(cmd.Context(), params)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

	{
		cmd := &cobra.Command{
			Use:   "create-unallowlist-by-id <findingId>",
			Short: "Unallowlist Finding",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				client := getClient()
				params := url.Values{}
				flagMap := map[string]string{
					"azure-organization-id": "azureOrganizationId",
					"bitbucket-workspace-id": "bitbucketWorkspaceId",
					"github-owner-id": "githubOwnerId",
					"gitlab-group-id": "gitlabGroupId",
					"installation-id": "installationId",
					"azure-repository-id": "azureRepositoryId",
					"github-repository-id": "githubRepositoryId",
					"github-team-id": "githubTeamId",
					"bitbucket-repository-id": "bitbucketRepositoryId",
				}
				cmd.Flags().Visit(func(f *pflag.Flag) {
					if apiName, ok := flagMap[f.Name]; ok {
						params.Set(apiName, f.Value.String())
					} else {
						params.Set(f.Name, f.Value.String())
					}
				})
				if len(args) > 0 {
					params.Set("findingId", args[0])
				}
				result, err := client.CreateScpmFindingsFindingIdUnallowlist(cmd.Context(), params, os.Stdin)
				if err != nil {
					return err
				}
				return output.Print(cmd, result)
			},
		}
		cmd.Flags().String("azure-organization-id", "", "The Azure organization ID")
		cmd.Flags().String("bitbucket-workspace-id", "", "The Bitbucket workspace ID")
		cmd.Flags().String("github-owner-id", "", "The Github owner ID")
		cmd.Flags().String("gitlab-group-id", "", "The GitLab group ID")
		cmd.Flags().String("installation-id", "", "The Nullify installation ID")
		cmd.Flags().String("azure-repository-id", "", "Filter by Azure repository IDs")
		cmd.Flags().String("github-repository-id", "", "Filter by GitHub repository IDs")
		cmd.Flags().String("github-team-id", "", "Filter by GitHub team ID")
		cmd.Flags().String("bitbucket-repository-id", "", "Filter by Bitbucket repository IDs")
		serviceCmd.AddCommand(cmd)
	}

}
