// Code generated by scripts/generate/main.go. DO NOT EDIT.
package models

type EndpointsGetInfrastructureGraphDownloadOutput struct {
	AccountID string `json:"accountId"`
	DownloadURL string `json:"downloadUrl"`
	ExpiresAt string `json:"expiresAt"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetInfrastructureGraphOutput struct {
	Graph *GraphGraph `json:"graph,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetInfrastructureGraphSummaryOutput struct {
	AccountCount int `json:"accountCount"`
	CombinedGraphExpiresAt string `json:"combinedGraphExpiresAt"`
	CombinedGraphURL *string `json:"combinedGraphUrl,omitempty"`
	GraphInfo *EndpointsInfrastructureGraphInfo `json:"graphInfo,omitempty"`
	Graphs []EndpointsInfrastructureGraphDownloadInfo `json:"graphs,omitempty"`
	IntegrationStatus EndpointsIntegrationStatus `json:"integrationStatus"`
	LastUpdated string `json:"lastUpdated"`
	TotalEdgeCount int `json:"totalEdgeCount"`
	TotalNodeCount int `json:"totalNodeCount"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetInfrastructureGraphVersionOutput struct {
	Graph *GraphGraph `json:"graph,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsInfrastructureGraphDownloadInfo struct {
	AccountID string `json:"accountId"`
	DownloadURL string `json:"downloadUrl"`
	EdgeCount int `json:"edgeCount"`
	ExpiresAt string `json:"expiresAt"`
	GeneratedAt string `json:"generatedAt"`
	GraphID *string `json:"graphId,omitempty"`
	GraphType *string `json:"graphType,omitempty"`
	NodeCount int `json:"nodeCount"`
	Region *string `json:"region,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsInfrastructureGraphSummary struct {
	AccountID string `json:"accountId"`
	EdgeCount int `json:"edgeCount"`
	GeneratedAt string `json:"generatedAt"`
	GeneratedBy string `json:"generatedBy"`
	GraphID string `json:"graphId"`
	GraphType string `json:"graphType"`
	LastModified string `json:"lastModified"`
	NodeCount int `json:"nodeCount"`
	Region *string `json:"region,omitempty"`
	S3Key *string `json:"s3Key,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
	Version string `json:"version"`
}

type EndpointsIntegrationStatus string

const (
	EndpointsIntegrationStatusPending EndpointsIntegrationStatus = "pending"
	EndpointsIntegrationStatusReady EndpointsIntegrationStatus = "ready"
)

type EndpointsListInfrastructureGraphVersionsOutput struct {
	AccountID string `json:"accountId"`
	Count int `json:"count"`
	Version *string `json:"version,omitempty"`
	Versions []string `json:"versions,omitempty"`
}

type EndpointsListInfrastructureGraphsOutput struct {
	Count int `json:"count"`
	Graphs []EndpointsInfrastructureGraphSummary `json:"graphs,omitempty"`
	Version *string `json:"version,omitempty"`
}

