// Code generated by scripts/generate/main.go. DO NOT EDIT.
package models

import "encoding/json"

type ActionsPendingAction struct {
}

type AuditToolCallAuditRecord struct {
}

type EndpointsCampaignRunDetail struct {
	AgentCostCredits *int64 `json:"agentCostCredits,omitempty"`
	AgentInputTokens *int64 `json:"agentInputTokens,omitempty"`
	AgentOutputTokens *int64 `json:"agentOutputTokens,omitempty"`
	CampaignID string `json:"campaignId"`
	EndedAt *string `json:"endedAt,omitempty"`
	ErrorSummary *string `json:"errorSummary,omitempty"`
	ID string `json:"id"`
	Plan *json.RawMessage `json:"plan,omitempty"`
	ProviderID string `json:"providerId"`
	StartedAt string `json:"startedAt"`
	State string `json:"state"`
	TenantID string `json:"tenantId"`
	ToolEventCount *int32 `json:"toolEventCount,omitempty"`
}

type EndpointsCampaignRunSummary struct {
	AgentCostCredits *int64 `json:"agentCostCredits,omitempty"`
	AgentInputTokens *int64 `json:"agentInputTokens,omitempty"`
	AgentOutputTokens *int64 `json:"agentOutputTokens,omitempty"`
	CampaignID string `json:"campaignId"`
	EndedAt *string `json:"endedAt,omitempty"`
	ErrorSummary *string `json:"errorSummary,omitempty"`
	ID string `json:"id"`
	ProviderID string `json:"providerId"`
	StartedAt string `json:"startedAt"`
	State string `json:"state"`
	TenantID string `json:"tenantId"`
	ToolEventCount *int32 `json:"toolEventCount,omitempty"`
}

type EndpointsCustomerQuestionSetResponse struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	CustomMessage *string `json:"customMessage,omitempty"`
	GeneratedMemoryIds []string `json:"generatedMemoryIds,omitempty"`
	ID *string `json:"id,omitempty"`
	Questions []ModelsCustomerQuestion `json:"questions,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type EndpointsDeleteAllCustomerQuestionSetsOutput struct {
	DeletedCount int64 `json:"deletedCount"`
	Version *string `json:"version,omitempty"`
}

type EndpointsDeleteChatSessionOutput struct {
	Success *bool `json:"success,omitempty"`
}

type EndpointsDeleteCustomerQuestionOutput struct {
	Success bool `json:"success"`
	Version *string `json:"version,omitempty"`
}

type EndpointsDeleteCustomerQuestionSetOutput struct {
	Success bool `json:"success"`
	Version *string `json:"version,omitempty"`
}

type EndpointsDeleteEventOutput struct {
	Version *string `json:"version,omitempty"`
}

type EndpointsGenerateDefaultCampaignsOutput struct {
	Message string `json:"message"`
	Version string `json:"version"`
}

type EndpointsGetAllCampaignsFindingsOutput struct {
	Findings []ModelsFindingProgress `json:"findings,omitempty"`
	NumItems int `json:"numItems"`
	Version string `json:"version"`
}

type EndpointsGetCampaignEventsOutput struct {
	Events []ModelsManagerEvent `json:"events,omitempty"`
	HasNextPage bool `json:"hasNextPage"`
	NumItems int `json:"numItems"`
	PullRequestTitles map[string]string `json:"pullRequestTitles,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetCampaignFindingsOutput struct {
	CampaignID string `json:"campaignId"`
	FindingIDs []string `json:"findingIDs,omitempty"`
	NumItems int `json:"numItems"`
	Version string `json:"version"`
}

type EndpointsGetCampaignMetricsRefreshOutput struct {
	Response string `json:"response"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetCampaignOutput struct {
	Campaign *ModelsCampaign `json:"campaign,omitempty"`
	MappedFindingIds []string `json:"mappedFindingIds,omitempty"`
	MappedFindings []ModelsFindingProgress `json:"mappedFindings,omitempty"`
	Version string `json:"version"`
}

type EndpointsGetCampaignPreviewOutput struct {
	Campaign *ModelsCampaignPreview `json:"campaign,omitempty"`
	NumItems int `json:"numItems"`
	Version string `json:"version"`
}

type EndpointsGetCampaignPreviewsOutput struct {
	Campaigns []ModelsCampaignPreview `json:"campaigns,omitempty"`
	Findings []ModelsFindingProgress `json:"findings,omitempty"`
	NumItems int `json:"numItems"`
	Version string `json:"version"`
}

type EndpointsGetCampaignRunOutput struct {
	Run EndpointsCampaignRunDetail `json:"run"`
}

type EndpointsGetCampaignRunsOutput struct {
	NextCursor *string `json:"nextCursor,omitempty"`
	Runs []EndpointsCampaignRunSummary `json:"runs,omitempty"`
}

type EndpointsGetCampaignSummariesOutput struct {
	NumItems int `json:"numItems"`
	Summaries []ModelsPlanResponseSummary `json:"summaries,omitempty"`
	Version string `json:"version"`
}

type EndpointsGetCampaignsOutput struct {
	Campaigns []ModelsCampaign `json:"campaigns,omitempty"`
	NumItems int `json:"numItems"`
	Version string `json:"version"`
}

type EndpointsGetChatSessionActionsOutput struct {
	Actions []ActionsPendingAction `json:"actions,omitempty"`
}

type EndpointsGetChatSessionAuditOutput struct {
	NextToken *string `json:"nextToken,omitempty"`
	Records []AuditToolCallAuditRecord `json:"records,omitempty"`
}

type EndpointsGetChatSessionHistoryOutput struct {
	Messages []ModelsComment `json:"messages,omitempty"`
}

type EndpointsGetChatSessionOutput struct {
	Session *SessionsChatSession `json:"session,omitempty"`
}

type EndpointsGetCreditsOutput struct {
	Credits ModelsCredits `json:"credits"`
	Version string `json:"version"`
}

type EndpointsGetCustomerQuestionSetOutput struct {
	QuestionSet EndpointsCustomerQuestionSetResponse `json:"questionSet"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetCustomerQuestionSetsOutput struct {
	NumItems int `json:"numItems"`
	QuestionSets []EndpointsCustomerQuestionSetResponse `json:"questionSets,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetDefaultCampaignsOutput struct {
	Campaigns []ModelsCampaign `json:"campaigns,omitempty"`
	NumItems int `json:"numItems"`
	Version string `json:"version"`
}

type EndpointsGetEscalationsOutput struct {
	Escalations []ModelsEscalation `json:"escalations,omitempty"`
	NumItems int `json:"numItems"`
	Version string `json:"version"`
}

type EndpointsGetEventsOutput struct {
	Events []ModelsManagerEvent `json:"events,omitempty"`
	NumItems int `json:"numItems"`
	Version string `json:"version"`
}

type EndpointsGetFindingEventsOutput struct {
	Events []ModelsManagerEvent `json:"events,omitempty"`
	NextCursor *string `json:"nextCursor,omitempty"`
	NumItems int `json:"numItems"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetManagerConfigOutput struct {
	Config ModelsManagerConfig `json:"config"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetManagerGroundRulesOutput struct {
	GroundRules *ModelsManagerGroundRules `json:"groundRules,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetManagerMetricsOutput struct {
	AutofixDuration *int `json:"autofixDuration,omitempty"`
	BacklogSearches *int `json:"backlogSearches,omitempty"`
	DetectionDuration *int `json:"detectionDuration,omitempty"`
	EscalatedFindings *int `json:"escalatedFindings,omitempty"`
	Escalations *int `json:"escalations,omitempty"`
	FindingsInBacklog int `json:"findingsInBacklog"`
	FindingsInProgress int `json:"findingsInProgress"`
	FindingsResolved int `json:"findingsResolved"`
	InternetSearchCount *int `json:"internetSearchCount,omitempty"`
	MappedFindings []ModelsFindingProgress `json:"mappedFindings,omitempty"`
	MeanTimeAutofixToInProgress *int `json:"meanTimeAutofixToInProgress,omitempty"`
	MeanTimeInProgressToResolved *int `json:"meanTimeInProgressToResolved,omitempty"`
	MeanTimeToAutofix *int `json:"meanTimeToAutofix,omitempty"`
	MeanTimeToDetectAndTriage *int `json:"meanTimeToDetectAndTriage,omitempty"`
	MeanTimeToResolve int `json:"meanTimeToResolve"`
	MeanTimeToTriage *int `json:"meanTimeToTriage,omitempty"`
	MedianTimeAutofixToInProgress *int `json:"medianTimeAutofixToInProgress,omitempty"`
	MedianTimeInProgressToResolved *int `json:"medianTimeInProgressToResolved,omitempty"`
	MedianTimeToAutofix *int `json:"medianTimeToAutofix,omitempty"`
	MedianTimeToDetectAndTriage *int `json:"medianTimeToDetectAndTriage,omitempty"`
	MedianTimeToTriage *int `json:"medianTimeToTriage,omitempty"`
	MessageCount *int `json:"messageCount,omitempty"`
	PlansGenerated *int `json:"plansGenerated,omitempty"`
	PrCloseCount *int `json:"prCloseCount,omitempty"`
	PrCommentCount *int `json:"prCommentCount,omitempty"`
	PrCreateCount *int `json:"prCreateCount,omitempty"`
	PreviewMessageCount *int `json:"previewMessageCount,omitempty"`
	StoryPointsConsumed *int `json:"storyPointsConsumed,omitempty"`
	TasksAssigned *int `json:"tasksAssigned,omitempty"`
	TicketCloseCount *int `json:"ticketCloseCount,omitempty"`
	TicketCommentCount *int `json:"ticketCommentCount,omitempty"`
	TicketCreateCount *int `json:"ticketCreateCount,omitempty"`
	TimeSaved *int `json:"timeSaved,omitempty"`
	TimeSavedAssigning *int `json:"timeSavedAssigning,omitempty"`
	TotalRemediationDuration *int `json:"totalRemediationDuration,omitempty"`
	TriageDuration *int `json:"triageDuration,omitempty"`
	Version string `json:"version"`
}

type EndpointsGetManagerStateOutput struct {
	CurrentState ModelsManagerState `json:"currentState"`
	Version string `json:"version"`
}

type EndpointsGetManagerStatesOutput struct {
	StateHistory ModelsManagerStates `json:"stateHistory"`
	Version string `json:"version"`
}

type EndpointsGetPlansOutput struct {
	NumItems int `json:"numItems"`
	Plans []ModelsPlan `json:"plans,omitempty"`
	Version string `json:"version"`
}

type EndpointsGetStrategyOutput struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	ID *string `json:"id,omitempty"`
	Quarters []ModelsStrategyQuarterGoal `json:"quarters,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Version *int `json:"version,omitempty"`
}

type EndpointsGetThreatInvestigationOutput struct {
	Events []ModelsManagerEvent `json:"events,omitempty"`
	ThreatInvestigation ModelsThreatInvestigation `json:"threatInvestigation"`
	Version *string `json:"version,omitempty"`
}

type EndpointsGetThreatInvestigationsOutput struct {
	NumItems int `json:"numItems"`
	ThreatInvestigations []ModelsThreatInvestigation `json:"threatInvestigations,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsListChatSessionsOutput struct {
	NextToken *string `json:"nextToken,omitempty"`
	Sessions []SessionsChatSession `json:"sessions,omitempty"`
}

type EndpointsListStrategyVersionsOutput struct {
	NumItems *int `json:"numItems,omitempty"`
	Strategies []ModelsStrategy `json:"strategies,omitempty"`
}

type EndpointsManagerConfigInput struct {
	EnableActions *bool `json:"enableActions,omitempty"`
	Initialized bool `json:"initialized"`
}

type EndpointsPatchCampaignInput struct {
	CreatedAfter *string `json:"createdAfter,omitempty"`
	CreatedBefore *string `json:"createdBefore,omitempty"`
	Description *string `json:"description,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	FindingIds []string `json:"findingIds,omitempty"`
	GeneratedReasoning *string `json:"generatedReasoning,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
	LimitPerType *int `json:"limitPerType,omitempty"`
	MaxStoryPoints *int `json:"maxStoryPoints,omitempty"`
	MinPriority *float64 `json:"minPriority,omitempty"`
	NoEndDate *bool `json:"noEndDate,omitempty"`
	Owner *string `json:"owner,omitempty"`
	PriorityLabels []string `json:"priorityLabels,omitempty"`
	RepositoryNames []string `json:"repositoryNames,omitempty"`
	SortByColumns *string `json:"sortByColumns,omitempty"`
	SortByDirection *string `json:"sortByDirection,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	Summary *string `json:"summary,omitempty"`
	TeamIDs []string `json:"teamIDs,omitempty"`
	TeamNames []string `json:"teamNames,omitempty"`
	Title *string `json:"title,omitempty"`
	Types []string `json:"types,omitempty"`
	UserNames []string `json:"userNames,omitempty"`
	VulnerabilityCVEIds []string `json:"vulnerabilityCVEIds,omitempty"`
	VulnerabilityCWEIds []string `json:"vulnerabilityCWEIds,omitempty"`
}

type EndpointsPatchCampaignOutput struct {
	Campaign *ModelsCampaign `json:"campaign,omitempty"`
	CampaignID string `json:"campaignId"`
	Version string `json:"version"`
}

type EndpointsPatchChatSessionInput struct {
	Title *string `json:"title,omitempty"`
}

type EndpointsPatchChatSessionOutput struct {
	Success *bool `json:"success,omitempty"`
}

type EndpointsPatchCustomerQuestionAnswerInput struct {
	Answer json.RawMessage `json:"answer"`
}

type EndpointsPatchCustomerQuestionAnswerOutput struct {
	Success bool `json:"success"`
	Version *string `json:"version,omitempty"`
}

type EndpointsPatchEscalationsInput struct {
	Reasoning *string `json:"reasoning,omitempty"`
	Status *ModelsEscalationStatus `json:"status,omitempty"`
}

type EndpointsPatchGroundRulesInput struct {
	GroundRules *ModelsManagerGroundRules `json:"groundRules,omitempty"`
}

type EndpointsPatchGroundRulesOutput struct {
	GroundRules *ModelsManagerGroundRules `json:"groundRules,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsPatchStrategyInput struct {
	Quarters []ModelsStrategyQuarterGoal `json:"quarters,omitempty"`
}

type EndpointsPatchStrategyOutput struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	ID *string `json:"id,omitempty"`
	Quarters []ModelsStrategyQuarterGoal `json:"quarters,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Version *int `json:"version,omitempty"`
}

type EndpointsPatchThreatInvestigationInput struct {
	Action string `json:"action"`
}

type EndpointsPatchThreatInvestigationOutput struct {
	ThreatInvestigation ModelsThreatInvestigation `json:"threatInvestigation"`
	Version *string `json:"version,omitempty"`
}

type EndpointsPostCampaignInput struct {
	CreatedAfter *string `json:"createdAfter,omitempty"`
	CreatedBefore *string `json:"createdBefore,omitempty"`
	Description *string `json:"description,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	FindingIds []string `json:"findingIds,omitempty"`
	GeneratedReasoning *string `json:"generatedReasoning,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
	LimitPerType *int `json:"limitPerType,omitempty"`
	MaxStoryPoints *int `json:"maxStoryPoints,omitempty"`
	MinPriority *float64 `json:"minPriority,omitempty"`
	NoEndDate *bool `json:"noEndDate,omitempty"`
	Owner *string `json:"owner,omitempty"`
	PriorityLabels []string `json:"priorityLabels,omitempty"`
	RepositoryNames []string `json:"repositoryNames,omitempty"`
	SortByColumns *string `json:"sortByColumns,omitempty"`
	SortByDirection *string `json:"sortByDirection,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	Summary *string `json:"summary,omitempty"`
	TeamIDs []string `json:"teamIDs,omitempty"`
	TeamNames []string `json:"teamNames,omitempty"`
	Title *string `json:"title,omitempty"`
	Types []string `json:"types,omitempty"`
	UserNames []string `json:"userNames,omitempty"`
	VulnerabilityCVEIds []string `json:"vulnerabilityCVEIds,omitempty"`
	VulnerabilityCWEIds []string `json:"vulnerabilityCWEIds,omitempty"`
}

type EndpointsPostCampaignOutput struct {
	Campaign *ModelsCampaign `json:"campaign,omitempty"`
	CampaignID string `json:"campaignId"`
	Version string `json:"version"`
}

type EndpointsPostCreditsInput struct {
	Credits ModelsCreditsUpdate `json:"credits"`
}

type EndpointsPostCreditsOutput struct {
	Credits ModelsCredits `json:"credits"`
	Version string `json:"version"`
}

type EndpointsPostDeduplicateEventsInput struct {
	DryRun *bool `json:"dryRun,omitempty"`
	From *string `json:"from,omitempty"`
	Keep *string `json:"keep,omitempty"`
	Statuses []string `json:"statuses,omitempty"`
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`
	To *string `json:"to,omitempty"`
}

type EndpointsPostDeduplicateEventsOutput struct {
	DryRun *bool `json:"dryRun,omitempty"`
	Message string `json:"message"`
	PagesProcessed *int64 `json:"pagesProcessed,omitempty"`
	TotalDeleted *int64 `json:"totalDeleted,omitempty"`
	TotalDupes *int64 `json:"totalDupes,omitempty"`
	TotalOmitted *int64 `json:"totalOmitted,omitempty"`
	TotalScanned *int64 `json:"totalScanned,omitempty"`
	TotalUnique *int64 `json:"totalUnique,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsPostManagerConfigInput struct {
	Config EndpointsManagerConfigInput `json:"config"`
}

type EndpointsPostManagerConfigOutput struct {
	Config ModelsManagerConfig `json:"config"`
	Version *string `json:"version,omitempty"`
}

type EndpointsPostManagerGroundRulesInput struct {
	GroundRules *ModelsManagerGroundRules `json:"groundRules,omitempty"`
}

type EndpointsPostManagerGroundRulesOutput struct {
	GroundRules *ModelsManagerGroundRules `json:"groundRules,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsPostThreatInvestigationInput struct {
	Advice *string `json:"advice,omitempty"`
	AffectedPackages []ModelsThreatInvestigationAffectedPackage `json:"affectedPackages,omitempty"`
	ArticleLinks []string `json:"articleLinks,omitempty"`
	CveIds []string `json:"cveIds,omitempty"`
	Cvss *float64 `json:"cvss,omitempty"`
	Description *string `json:"description,omitempty"`
	Ecosystem *string `json:"ecosystem,omitempty"`
	Keywords *string `json:"keywords,omitempty"`
	Severity *string `json:"severity,omitempty"`
	Title string `json:"title"`
}

type EndpointsPostThreatInvestigationOutput struct {
	Existing *bool `json:"existing,omitempty"`
	ThreatInvestigation ModelsThreatInvestigation `json:"threatInvestigation"`
	Version *string `json:"version,omitempty"`
}

type EndpointsTriggerCampaignsOrchestratorInput struct {
	CampaignID *string `json:"campaignId,omitempty"`
	Mode *string `json:"mode,omitempty"`
}

type EndpointsTriggerCampaignsOrchestratorOutput struct {
	Message string `json:"message"`
	Response *string `json:"response,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsTriggerStrategyOutput struct {
	Message *string `json:"message,omitempty"`
	Version *string `json:"version,omitempty"`
}

type EndpointsTriggerTacitKnowledgeOutput struct {
	Message *string `json:"message,omitempty"`
	Version *string `json:"version,omitempty"`
}

type ModelsAzureCommentProvider struct {
	CommentID int `json:"commentId"`
	ThreadID int `json:"threadId"`
}

type ModelsBitbucketCommentProvider struct {
	CommentID int64 `json:"commentId"`
}

type ModelsCampaign struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	Events []ModelsManagerEvent `json:"events,omitempty"`
	Generated *bool `json:"generated,omitempty"`
	GeneratedReasoning *string `json:"generatedReasoning,omitempty"`
	ID *string `json:"id,omitempty"`
	ImmediateRemediation *bool `json:"immediateRemediation,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
	Metrics *ModelsMetrics `json:"metrics,omitempty"`
	NoEndDate *bool `json:"noEndDate,omitempty"`
	Owner *string `json:"owner,omitempty"`
	SelectionCriteria *ModelsSelectionCriteria `json:"selectionCriteria,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	Status *string `json:"status,omitempty"`
	Summary *string `json:"summary,omitempty"`
	Title *string `json:"title,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type ModelsCampaignPreview struct {
	AutofixTimeTotal *int `json:"autofixTimeTotal,omitempty"`
	BacklogSearches *int `json:"backlogSearches,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	Description string `json:"description"`
	DetectionTimeTotal *int `json:"detectionTimeTotal,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	EscalatedFindings *int `json:"escalatedFindings,omitempty"`
	Escalations *int `json:"escalations,omitempty"`
	EstimatedBacklogStoryPoints *int `json:"estimatedBacklogStoryPoints,omitempty"`
	FindingTypes []string `json:"findingTypes,omitempty"`
	FindingsAllowlistedCount *int `json:"findingsAllowlistedCount,omitempty"`
	FindingsCount *int `json:"findingsCount,omitempty"`
	FindingsInBacklogCount *int `json:"findingsInBacklogCount,omitempty"`
	FindingsResolvedCount *int `json:"findingsResolvedCount,omitempty"`
	FindingsWithAllowlistPRCount *int `json:"findingsWithAllowlistPRCount,omitempty"`
	FindingsWithOpenAutoFixPRCount *int `json:"findingsWithOpenAutoFixPRCount,omitempty"`
	FindingsWithOpenTicketCount *int `json:"findingsWithOpenTicketCount,omitempty"`
	Generated *bool `json:"generated,omitempty"`
	GeneratedReasoning string `json:"generatedReasoning"`
	ID *string `json:"id,omitempty"`
	InternetSearchCount *int `json:"internetSearchCount,omitempty"`
	IsActive bool `json:"isActive"`
	MappedFindingIds []string `json:"mappedFindingIds,omitempty"`
	MaxStoryPoints *int `json:"maxStoryPoints,omitempty"`
	MeanTimeToDetectAndTriage *int `json:"meanTimeToDetectAndTriage,omitempty"`
	MeanTimeToMerge *int `json:"meanTimeToMerge,omitempty"`
	MeanTimeToPullRequestCreation *int `json:"meanTimeToPullRequestCreation,omitempty"`
	MeanTimeToResolve *int `json:"meanTimeToResolve,omitempty"`
	MeanTimeToReview *int `json:"meanTimeToReview,omitempty"`
	MedianTimeToDetectAndTriage *int `json:"medianTimeToDetectAndTriage,omitempty"`
	MedianTimeToMerge *int `json:"medianTimeToMerge,omitempty"`
	MedianTimeToPullRequestCreation *int `json:"medianTimeToPullRequestCreation,omitempty"`
	MedianTimeToResolve *int `json:"medianTimeToResolve,omitempty"`
	MedianTimeToReview *int `json:"medianTimeToReview,omitempty"`
	MessageCount *int `json:"messageCount,omitempty"`
	NoEndDate *bool `json:"noEndDate,omitempty"`
	PlansGenerated *int `json:"plansGenerated,omitempty"`
	PrCloseCount *int `json:"prCloseCount,omitempty"`
	PrCommentCount *int `json:"prCommentCount,omitempty"`
	PrCreateCount *int `json:"prCreateCount,omitempty"`
	PreviewMessageCount *int `json:"previewMessageCount,omitempty"`
	PriorityLabels []ModelsPriorityLabel `json:"priorityLabels,omitempty"`
	RepositoryNames []string `json:"repositoryNames,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	Status string `json:"status"`
	StoryPointsConsumed *int `json:"storyPointsConsumed,omitempty"`
	TasksAssigned *int `json:"tasksAssigned,omitempty"`
	TicketCloseCount *int `json:"ticketCloseCount,omitempty"`
	TicketCommentCount *int `json:"ticketCommentCount,omitempty"`
	TicketCreateCount *int `json:"ticketCreateCount,omitempty"`
	TimeSaved *int `json:"timeSaved,omitempty"`
	TimeSavedAssigning *int `json:"timeSavedAssigning,omitempty"`
	Title string `json:"title"`
	TriageTimeTotal *int `json:"triageTimeTotal,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Users []string `json:"users,omitempty"`
}

type ModelsComment struct {
	Body string `json:"body"`
	CommentProvider *ModelsCommentProvider `json:"commentProvider,omitempty"`
	CreatedAt string `json:"createdAt"`
	ID *string `json:"id,omitempty"`
	IsNullify bool `json:"isNullify"`
	UpdatedAt string `json:"updatedAt"`
	UserID string `json:"userId"`
	UserName string `json:"userName"`
}

type ModelsCommentProvider struct {
	Azure *ModelsAzureCommentProvider `json:"azure,omitempty"`
	Bitbucket *ModelsBitbucketCommentProvider `json:"bitbucket,omitempty"`
	Github *ModelsGitHubCommentProvider `json:"github,omitempty"`
	Gitlab *ModelsGitLabCommentProvider `json:"gitlab,omitempty"`
	ID *ModelsProviderID `json:"id,omitempty"`
	Jira *ModelsJiraCommentProvider `json:"jira,omitempty"`
	Linear *ModelsLinearCommentProvider `json:"linear,omitempty"`
	Slack *ModelsSlackCommentProvider `json:"slack,omitempty"`
	Teams *ModelsTeamsCommentProvider `json:"teams,omitempty"`
}

type ModelsCredits struct {
	Balance int `json:"balance"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type ModelsCreditsUpdate struct {
	Increment *int64 `json:"increment,omitempty"`
}

type ModelsEscalation struct {
	CampaignIds []string `json:"campaignIds,omitempty"`
	CreatedAt string `json:"createdAt"`
	FindingID string `json:"findingId"`
	ID *string `json:"id,omitempty"`
	PullRequestIds []string `json:"pullRequestIds,omitempty"`
	Reasoning string `json:"reasoning"`
	Status ModelsEscalationStatus `json:"status"`
	TicketIds []string `json:"ticketIds,omitempty"`
	UpdatedAt string `json:"updatedAt"`
}

type ModelsEscalationStatus string

const (
	ModelsEscalationStatusOpen ModelsEscalationStatus = "OPEN"
	ModelsEscalationStatusResolved ModelsEscalationStatus = "RESOLVED"
)

type ModelsFindingProgress struct {
	AutofixDuration *int `json:"autofixDuration,omitempty"`
	AutofixedAt *string `json:"autofixedAt,omitempty"`
	CreatedAt string `json:"createdAt"`
	DetectionDuration *int `json:"detectionDuration,omitempty"`
	DiscoveredAt *string `json:"discoveredAt,omitempty"`
	FindingID string `json:"findingId"`
	FindingType ModelsFindingType `json:"findingType"`
	InProgressAt *string `json:"inProgressAt,omitempty"`
	ResolvedAt *string `json:"resolvedAt,omitempty"`
	Status ModelsFindingStatus `json:"status"`
	TimeSaved *int `json:"timeSaved,omitempty"`
	TotalRemediationDuration *int `json:"totalRemediationDuration,omitempty"`
	TriageDuration *int `json:"triageDuration,omitempty"`
	TriagedAt *string `json:"triagedAt,omitempty"`
	UpdatedAt string `json:"updatedAt"`
}

type ModelsFindingStatus string

const (
	ModelsFindingStatusBacklog ModelsFindingStatus = "BACKLOG"
	ModelsFindingStatusInProgress ModelsFindingStatus = "IN_PROGRESS"
	ModelsFindingStatusResolved ModelsFindingStatus = "RESOLVED"
)

type ModelsGitHubCommentProvider struct {
	CommentID int64 `json:"commentId"`
	CommentNodeID string `json:"commentNodeId"`
}

type ModelsGitLabCommentProvider struct {
	CommentID int64 `json:"commentId"`
	ThreadID string `json:"threadId"`
}

type ModelsJiraCommentProvider struct {
	CommentID string `json:"commentId"`
}

type ModelsLinearCommentProvider struct {
	CommentID string `json:"commentId"`
}

type ModelsManagerConfig struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	EnableActions *bool `json:"enableActions,omitempty"`
	ID *string `json:"id,omitempty"`
	Initialized bool `json:"initialized"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type ModelsManagerEvent struct {
	ActionType string `json:"actionType"`
	CampaignIds []string `json:"campaignIds,omitempty"`
	CreatedAt string `json:"createdAt"`
	Description string `json:"description"`
	FindingIds []string `json:"findingIds,omitempty"`
	ID string `json:"id"`
	MetaData map[string]string `json:"metaData,omitempty"`
	PullRequestIds []string `json:"pullRequestIds,omitempty"`
	Reasoning string `json:"reasoning"`
	RepositoryIds []string `json:"repositoryIds,omitempty"`
	Status string `json:"status"`
	ThreatInvestigationIds []string `json:"threatInvestigationIds,omitempty"`
	TicketIds []string `json:"ticketIds,omitempty"`
	UserIds []string `json:"userIds,omitempty"`
}

type ModelsManagerGroundRules struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	DisableChannelMessages bool `json:"disableChannelMessages"`
	DisableDirectMessages bool `json:"disableDirectMessages"`
	DisablePRClosure bool `json:"disablePRClosure"`
	DisablePRComments bool `json:"disablePRComments"`
	DisablePRCreation bool `json:"disablePRCreation"`
	DisableReviewerCandidateSelection *bool `json:"disableReviewerCandidateSelection,omitempty"`
	DisableTicketClosure bool `json:"disableTicketClosure"`
	DisableTicketComments bool `json:"disableTicketComments"`
	DisableTicketCreation bool `json:"disableTicketCreation"`
	ID *string `json:"id,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type ModelsManagerState struct {
	Content string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type ModelsManagerStates = []ModelsManagerState

type ModelsMetrics struct {
	BacklogSearches *int `json:"backlogSearches,omitempty"`
	EscalatedFindings *int `json:"escalatedFindings,omitempty"`
	Escalations *int `json:"escalations,omitempty"`
	FindingsAnalysis *ModelsFindingsMetrics `json:"findingsAnalysis,omitempty"`
	InternetSearchCount *int `json:"internetSearchCount,omitempty"`
	MessageCount *int `json:"messageCount,omitempty"`
	PlansGenerated *int `json:"plansGenerated,omitempty"`
	PrCloseCount *int `json:"prCloseCount,omitempty"`
	PrCommentCount *int `json:"prCommentCount,omitempty"`
	PrCreateCount *int `json:"prCreateCount,omitempty"`
	PreviewMessageCount *int `json:"previewMessageCount,omitempty"`
	StoryPointsConsumed *int `json:"storyPointsConsumed,omitempty"`
	TasksAssigned *int `json:"tasksAssigned,omitempty"`
	TicketCloseCount *int `json:"ticketCloseCount,omitempty"`
	TicketCommentCount *int `json:"ticketCommentCount,omitempty"`
	TicketCreateCount *int `json:"ticketCreateCount,omitempty"`
	TimeSavedAssigning *int `json:"timeSavedAssigning,omitempty"`
}

type ModelsPlan struct {
	CreatedAt string `json:"createdAt"`
	Events []ModelsManagerEvent `json:"events,omitempty"`
	ID *string `json:"id,omitempty"`
	Response *ModelsPlanResponse `json:"response,omitempty"`
}

type ModelsPlanResponse struct {
	ActionsExecuted *ModelsPlanResponseActionsExecuted `json:"actionsExecuted,omitempty"`
	Preview *ModelsPlanResponsePreview `json:"preview,omitempty"`
	Summary ModelsPlanResponseSummary `json:"summary"`
	Thoughts []ModelsPlanResponseThought `json:"thoughts,omitempty"`
	ThreatReport *ModelsPlanResponseThreatReport `json:"threatReport,omitempty"`
}

type ModelsPlanResponseActionsExecuted struct {
	ChannelMessagesSent int `json:"channelMessagesSent"`
	DirectMessagesSent int `json:"directMessagesSent"`
	FindingsAllowlisted int `json:"findingsAllowlisted"`
	FindingsEscalated int `json:"findingsEscalated"`
	PrCommentsCreated int `json:"prCommentsCreated"`
	PrsClosed int `json:"prsClosed"`
	PrsCreated int `json:"prsCreated"`
	PrsReassigned int `json:"prsReassigned"`
	TicketCommentCreated int `json:"ticketCommentCreated"`
	TicketsClosed int `json:"ticketsClosed"`
	TicketsCreated int `json:"ticketsCreated"`
	TicketsReassigned int `json:"ticketsReassigned"`
}

type ModelsPlanResponseCampaignSummary struct {
	CampaignID string `json:"campaignId"`
	Content string `json:"content"`
	Status string `json:"status"`
}

type ModelsPlanResponsePreview struct {
	ProjectedActions ModelsPlanResponsePreviewProjectedActions `json:"projectedActions"`
	Thoughts string `json:"thoughts"`
}

type ModelsPlanResponsePreviewProjectedActions struct {
	AllowlistFindings []ModelsProjectedAllowlistFinding `json:"allowlistFindings,omitempty"`
	CloseFixPullRequests []ModelsProjectedCloseFixPullRequest `json:"closeFixPullRequests,omitempty"`
	CloseTickets []ModelsProjectedCloseTicket `json:"closeTickets,omitempty"`
	CommentOnFixPullRequests []ModelsProjectedCommentOnFixPullRequest `json:"commentOnFixPullRequests,omitempty"`
	CommentOnTickets []ModelsProjectedCommentOnTicket `json:"commentOnTickets,omitempty"`
	CreateFixPullRequests []ModelsProjectedCreateFixPullRequest `json:"createFixPullRequests,omitempty"`
	CreateTickets []ModelsProjectedCreateTicket `json:"createTickets,omitempty"`
	EscalateFindings []ModelsProjectedEscalateFinding `json:"escalateFindings,omitempty"`
	MessageChannels []ModelsProjectedMessageChannel `json:"messageChannels,omitempty"`
	ReassignFixPullRequests []ModelsProjectedReassignFixPullRequest `json:"reassignFixPullRequests,omitempty"`
	ReassignTickets []ModelsProjectedReassignTicket `json:"reassignTickets,omitempty"`
	SendDirectMessages []ModelsProjectedSendDirectMessage `json:"sendDirectMessages,omitempty"`
}

type ModelsPlanResponseSummary struct {
	Campaigns []ModelsPlanResponseCampaignSummary `json:"campaigns,omitempty"`
	Content string `json:"content"`
	CreatedAt *string `json:"createdAt,omitempty"`
}

type ModelsPlanResponseThought struct {
	Content string `json:"content"`
	CreatedAt string `json:"createdAt"`
	FindingID *string `json:"findingId,omitempty"`
}

type ModelsPlanResponseThreatReport struct {
	CreatedAt string `json:"createdAt"`
	Summary string `json:"summary"`
}

type ModelsProjectedAllowlistFinding struct {
	EstimatedDate string `json:"estimatedDate"`
	FindingID string `json:"findingId"`
	Reason string `json:"reason"`
}

type ModelsProjectedCloseFixPullRequest struct {
	EstimatedDate string `json:"estimatedDate"`
	PullRequestID string `json:"pullRequestId"`
	Reason string `json:"reason"`
}

type ModelsProjectedCloseTicket struct {
	EstimatedDate string `json:"estimatedDate"`
	Reason string `json:"reason"`
	TicketID string `json:"ticketId"`
}

type ModelsProjectedCommentOnFixPullRequest struct {
	EstimatedDate string `json:"estimatedDate"`
	PullRequestID string `json:"pullRequestId"`
	Reason string `json:"reason"`
}

type ModelsProjectedCommentOnTicket struct {
	EstimatedDate string `json:"estimatedDate"`
	Reason string `json:"reason"`
	TicketID string `json:"ticketId"`
}

type ModelsProjectedCreateFixPullRequest struct {
	EstimatedDate string `json:"estimatedDate"`
	FindingID string `json:"findingId"`
	Reason string `json:"reason"`
}

type ModelsProjectedCreateTicket struct {
	EstimatedDate string `json:"estimatedDate"`
	FindingID string `json:"findingId"`
	Reason string `json:"reason"`
}

type ModelsProjectedEscalateFinding struct {
	EstimatedDate string `json:"estimatedDate"`
	FindingID string `json:"findingId"`
	Reason string `json:"reason"`
}

type ModelsProjectedMessageChannel struct {
	ChannelID string `json:"channelId"`
	EstimatedDate string `json:"estimatedDate"`
	Reason string `json:"reason"`
	Topic string `json:"topic"`
}

type ModelsProjectedReassignFixPullRequest struct {
	EstimatedDate string `json:"estimatedDate"`
	PullRequestID string `json:"pullRequestId"`
	Reason string `json:"reason"`
}

type ModelsProjectedReassignTicket struct {
	EstimatedDate string `json:"estimatedDate"`
	Reason string `json:"reason"`
	TicketID string `json:"ticketId"`
}

type ModelsProjectedSendDirectMessage struct {
	EstimatedDate string `json:"estimatedDate"`
	FindingID string `json:"findingId"`
	Reason string `json:"reason"`
	UserID string `json:"userId"`
}

type ModelsSelectionCriteria struct {
	CreatedAfter *string `json:"createdAfter,omitempty"`
	CreatedBefore *string `json:"createdBefore,omitempty"`
	FindingIds []string `json:"findingIds,omitempty"`
	LimitPerType *int `json:"limitPerType,omitempty"`
	MaxStoryPoints *int `json:"maxStoryPoints,omitempty"`
	MinPriority *float64 `json:"minPriority,omitempty"`
	PriorityLabels []ModelsPriorityLabel `json:"priorityLabels,omitempty"`
	RepositoryNames []string `json:"repositoryNames,omitempty"`
	SortByColumns *string `json:"sortByColumns,omitempty"`
	SortByDirection *string `json:"sortByDirection,omitempty"`
	TeamIDs []string `json:"teamIDs,omitempty"`
	TeamNames []string `json:"teamNames,omitempty"`
	Types []ModelsFindingType `json:"types,omitempty"`
	UserNames []string `json:"userNames,omitempty"`
	VulnerabilityCVEIds []string `json:"vulnerabilityCVEIds,omitempty"`
	VulnerabilityCWEIds []string `json:"vulnerabilityCWEIds,omitempty"`
}

type ModelsSlackCommentProvider struct {
	ChannelID string `json:"channelId"`
	EventTs string `json:"eventTs"`
}

type ModelsStrategy struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	ID *string `json:"id,omitempty"`
	Quarters []ModelsStrategyQuarterGoal `json:"quarters,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Version *int `json:"version,omitempty"`
}

type ModelsStrategyQuarterGoal struct {
	Goals *string `json:"goals,omitempty"`
	Label *string `json:"label,omitempty"`
}

type ModelsTeamsCommentProvider struct {
	ChannelID string `json:"channelId"`
	ChatID string `json:"chatId"`
	MessageID string `json:"messageId"`
}

type ModelsThreatInvestigation struct {
	Advice *string `json:"advice,omitempty"`
	ClientImpact *ModelsThreatInvestigationClientImpact `json:"clientImpact,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	GeneralInfo *ModelsThreatInvestigationGeneralInfo `json:"generalInfo,omitempty"`
	ID *string `json:"id,omitempty"`
	Keywords *string `json:"keywords,omitempty"`
	Remediation *ModelsThreatInvestigationRemediation `json:"remediation,omitempty"`
	Report *ModelsThreatInvestigationReport `json:"report,omitempty"`
	Status string `json:"status"`
	Timeline *ModelsThreatInvestigationTimeline `json:"timeline,omitempty"`
	Type string `json:"type"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type ModelsThreatInvestigationAffectedPackage struct {
	AffectedRange *string `json:"affectedRange,omitempty"`
	AttributionType *string `json:"attributionType,omitempty"`
	Ecosystem *string `json:"ecosystem,omitempty"`
	Name *string `json:"name,omitempty"`
	Source *string `json:"source,omitempty"`
	SourceQuote *string `json:"sourceQuote,omitempty"`
	SourceURL *string `json:"sourceUrl,omitempty"`
}

type ModelsThreatInvestigationAffectedRepo struct {
	CiActivity *ModelsThreatInvestigationCIActivity `json:"ciActivity,omitempty"`
	FindingID *string `json:"findingId,omitempty"`
	FirstSeen *string `json:"firstSeen,omitempty"`
	IntroducedCommit *string `json:"introducedCommit,omitempty"`
	IsAutoFixable *bool `json:"isAutoFixable,omitempty"`
	IsDirect *bool `json:"isDirect,omitempty"`
	IsRemediated *bool `json:"isRemediated,omitempty"`
	LastSeen *string `json:"lastSeen,omitempty"`
	ManifestFile *string `json:"manifestFile,omitempty"`
	ManifestPath *string `json:"manifestPath,omitempty"`
	PackageName *string `json:"packageName,omitempty"`
	RemovedCommit *string `json:"removedCommit,omitempty"`
	RepositoryID *string `json:"repositoryId,omitempty"`
	RepositoryName *string `json:"repositoryName,omitempty"`
	RepositoryOwner *string `json:"repositoryOwner,omitempty"`
	Version *string `json:"version,omitempty"`
}

type ModelsThreatInvestigationCIActivity struct {
	BuildCount *int `json:"buildCount,omitempty"`
	IntroducedCommitBuilt *bool `json:"introducedCommitBuilt,omitempty"`
	SuccessfulBuildCount *int `json:"successfulBuildCount,omitempty"`
	WasBuilt *bool `json:"wasBuilt,omitempty"`
}

type ModelsThreatInvestigationClientImpact struct {
	AffectedRepoCount *int `json:"affectedRepoCount,omitempty"`
	AffectedRepos []ModelsThreatInvestigationAffectedRepo `json:"affectedRepos,omitempty"`
	FindingIds []string `json:"findingIds,omitempty"`
	TotalRepoCount *int `json:"totalRepoCount,omitempty"`
	UnaffectedRepoCount *int `json:"unaffectedRepoCount,omitempty"`
}

type ModelsThreatInvestigationGeneralInfo struct {
	AffectedPackages []ModelsThreatInvestigationAffectedPackage `json:"affectedPackages,omitempty"`
	ArticleLinks []string `json:"articleLinks,omitempty"`
	CveIds []string `json:"cveIds,omitempty"`
	Cvss *float64 `json:"cvss,omitempty"`
	Description *string `json:"description,omitempty"`
	DiscoveredAt *string `json:"discoveredAt,omitempty"`
	Ecosystem *string `json:"ecosystem,omitempty"`
	Exploitability *string `json:"exploitability,omitempty"`
	History *string `json:"history,omitempty"`
	Severity *ModelsSeverity `json:"severity,omitempty"`
	Title *string `json:"title,omitempty"`
}

type ModelsThreatInvestigationRemediation struct {
	AutoFixableCount *int `json:"autoFixableCount,omitempty"`
	AutofixPrIds []string `json:"autofixPrIds,omitempty"`
	CampaignID *string `json:"campaignId,omitempty"`
	CampaignStatus *string `json:"campaignStatus,omitempty"`
	CampaignTitle *string `json:"campaignTitle,omitempty"`
	FindingCount *int `json:"findingCount,omitempty"`
	PrCreateCount *int `json:"prCreateCount,omitempty"`
	PrFailedCount *int `json:"prFailedCount,omitempty"`
	ScanCompleted *bool `json:"scanCompleted,omitempty"`
	ScanTimestamp *string `json:"scanTimestamp,omitempty"`
}

type ModelsThreatInvestigationReport struct {
	ExecutiveSummary *string `json:"executiveSummary,omitempty"`
	ReferenceLinks []string `json:"referenceLinks,omitempty"`
	RemediationPlan *string `json:"remediationPlan,omitempty"`
	VulnerabilityDetail *string `json:"vulnerabilityDetail,omitempty"`
}

type ModelsThreatInvestigationTimeline struct {
	ImpactAssessedAt *string `json:"impactAssessedAt,omitempty"`
	InvestigationCompletedAt *string `json:"investigationCompletedAt,omitempty"`
	InvestigationCreatedAt *string `json:"investigationCreatedAt,omitempty"`
	RemediationStartedAt *string `json:"remediationStartedAt,omitempty"`
	ReportWrittenAt *string `json:"reportWrittenAt,omitempty"`
	ResearchCompletedAt *string `json:"researchCompletedAt,omitempty"`
	ResearchStartedAt *string `json:"researchStartedAt,omitempty"`
	ResolvedAt *string `json:"resolvedAt,omitempty"`
	ThreatDiscoveredAt *string `json:"threatDiscoveredAt,omitempty"`
}

type SessionsChatSession struct {
}

