// Code generated by scripts/generate/main.go. DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"strings"

	"github.com/nullify-platform/cli/internal/api/models"
)

var _ = bytes.NewReader
var _ = json.Marshal
var _ = strconv.FormatInt
var _ = strings.Replace
var _ = fmt.Sprintf
var _ = url.PathEscape
var _ = models.RequestScope{}

// ListCspmFindingsInput is the input for ListCspmFindings — Get CSPM Findings.
type ListCspmFindingsInput struct {
	AccountID *string `url:"accountId,omitempty" json:"-"`
	Limit *int `url:"limit,omitempty" json:"-"`
	NextToken *string `url:"nextToken,omitempty" json:"-"`
	Region *string `url:"region,omitempty" json:"-"`
	ResourceType *string `url:"resourceType,omitempty" json:"-"`
	ScanID *string `url:"scanId,omitempty" json:"-"`
	Severity *string `url:"severity,omitempty" json:"-"`
	Sort *string `url:"sort,omitempty" json:"-"`
	SortBy *string `url:"sortBy,omitempty" json:"-"`
	Status *string `url:"status,omitempty" json:"-"`
	models.RequestScope
}

// ListCspmFindings - Get CSPM Findings
// GET /cspm/findings
func (c *Client) ListCspmFindings(ctx context.Context, in ListCspmFindingsInput) (*models.EndpointsGetCSPMFindingsOutput, error) {
	path := "/cspm/findings"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if in.Limit != nil {
		query.Set("limit", strconv.Itoa(int(*in.Limit)))
	}
	if in.NextToken != nil {
		query.Set("nextToken", string(*in.NextToken))
	}
	if in.Sort != nil {
		query.Set("sort", string(*in.Sort))
	}
	if in.SortBy != nil {
		query.Set("sortBy", string(*in.SortBy))
	}
	if in.Severity != nil {
		query.Set("severity", string(*in.Severity))
	}
	if in.Status != nil {
		query.Set("status", string(*in.Status))
	}
	if in.AccountID != nil {
		query.Set("accountId", string(*in.AccountID))
	}
	if in.Region != nil {
		query.Set("region", string(*in.Region))
	}
	if in.ResourceType != nil {
		query.Set("resourceType", string(*in.ResourceType))
	}
	if in.ScanID != nil {
		query.Set("scanId", string(*in.ScanID))
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	data, err := c.do(ctx, "GET", fullURL, nil)
	if err != nil {
		return nil, err
	}
	var out models.EndpointsGetCSPMFindingsOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// GetCspmFindingsFindingIdInput is the input for GetCspmFindingsFindingId — Get CSPM Finding.
type GetCspmFindingsFindingIdInput struct {
	FindingID string `path:"findingId" json:"-"`
	models.RequestScope
}

// GetCspmFindingsFindingId - Get CSPM Finding
// GET /cspm/findings/{findingId}
func (c *Client) GetCspmFindingsFindingId(ctx context.Context, in GetCspmFindingsFindingIdInput) (*models.EndpointsGetCSPMFindingOutput, error) {
	path := "/cspm/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", url.PathEscape(in.FindingID), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	data, err := c.do(ctx, "GET", fullURL, nil)
	if err != nil {
		return nil, err
	}
	var out models.EndpointsGetCSPMFindingOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// ListCspmFindingsFindingIdAutofixActivityInput is the input for ListCspmFindingsFindingIdAutofixActivity — Get CSPM Finding Autofix Activity.
type ListCspmFindingsFindingIdAutofixActivityInput struct {
	FindingID string `path:"findingId" json:"-"`
	Limit *int32 `url:"limit,omitempty" json:"-"`
	SinceID *string `url:"since_id,omitempty" json:"-"`
	models.RequestScope
}

// ListCspmFindingsFindingIdAutofixActivity - Get CSPM Finding Autofix Activity
// GET /cspm/findings/{findingId}/autofix/activity
func (c *Client) ListCspmFindingsFindingIdAutofixActivity(ctx context.Context, in ListCspmFindingsFindingIdAutofixActivityInput) (*models.EndpointsGetAutofixActivityLogOutput, error) {
	path := "/cspm/findings/{findingId}/autofix/activity"
	path = strings.Replace(path, "{findingId}", url.PathEscape(in.FindingID), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if in.SinceID != nil {
		query.Set("since_id", string(*in.SinceID))
	}
	if in.Limit != nil {
		query.Set("limit", strconv.Itoa(int(*in.Limit)))
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	data, err := c.do(ctx, "GET", fullURL, nil)
	if err != nil {
		return nil, err
	}
	var out models.EndpointsGetAutofixActivityLogOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// ListCspmFindingsFindingIdAutofixCacheDiffInput is the input for ListCspmFindingsFindingIdAutofixCacheDiff — Get CSPM Finding Autofix Diff.
type ListCspmFindingsFindingIdAutofixCacheDiffInput struct {
	FindingID string `path:"findingId" json:"-"`
	models.RequestScope
}

// ListCspmFindingsFindingIdAutofixCacheDiff - Get CSPM Finding Autofix Diff
// GET /cspm/findings/{findingId}/autofix/cache/diff
func (c *Client) ListCspmFindingsFindingIdAutofixCacheDiff(ctx context.Context, in ListCspmFindingsFindingIdAutofixCacheDiffInput) (*models.EndpointsGetCSPMFindingAutofixDiffOutput, error) {
	path := "/cspm/findings/{findingId}/autofix/cache/diff"
	path = strings.Replace(path, "{findingId}", url.PathEscape(in.FindingID), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	data, err := c.do(ctx, "GET", fullURL, nil)
	if err != nil {
		return nil, err
	}
	var out models.EndpointsGetCSPMFindingAutofixDiffOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// CreateCspmFindingsFindingIdAutofixFixInput is the input for CreateCspmFindingsFindingIdAutofixFix — Post CSPM Finding Autofix.
type CreateCspmFindingsFindingIdAutofixFixInput struct {
	FindingID string `path:"findingId" json:"-"`
	Force *bool `json:"force,omitempty"`
	Message *string `json:"message,omitempty"`
	OriginCampaignID *string `json:"originCampaignId,omitempty"`
	models.RequestScope
}

// CreateCspmFindingsFindingIdAutofixFix - Post CSPM Finding Autofix
// POST /cspm/findings/{findingId}/autofix/fix
func (c *Client) CreateCspmFindingsFindingIdAutofixFix(ctx context.Context, in CreateCspmFindingsFindingIdAutofixFixInput) (*models.EndpointsPostCSPMFindingAutofixOutput, error) {
	path := "/cspm/findings/{findingId}/autofix/fix"
	path = strings.Replace(path, "{findingId}", url.PathEscape(in.FindingID), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	bodyBytes, err := json.Marshal(struct {
		Force *bool `json:"force,omitempty"`
		Message *string `json:"message,omitempty"`
		OriginCampaignID *string `json:"originCampaignId,omitempty"`
	}{
		Force: in.Force,
		Message: in.Message,
		OriginCampaignID: in.OriginCampaignID,
	})
	if err != nil {
		return nil, fmt.Errorf("marshal body: %w", err)
	}
	data, err := c.do(ctx, "POST", fullURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	var out models.EndpointsPostCSPMFindingAutofixOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// ListCspmFindingsFindingIdAutofixStateInput is the input for ListCspmFindingsFindingIdAutofixState — Get CSPM Finding Autofix State.
type ListCspmFindingsFindingIdAutofixStateInput struct {
	FindingID string `path:"findingId" json:"-"`
	models.RequestScope
}

// ListCspmFindingsFindingIdAutofixState - Get CSPM Finding Autofix State
// GET /cspm/findings/{findingId}/autofix/state
func (c *Client) ListCspmFindingsFindingIdAutofixState(ctx context.Context, in ListCspmFindingsFindingIdAutofixStateInput) (*models.EndpointsGetCSPMFindingAutofixStateOutput, error) {
	path := "/cspm/findings/{findingId}/autofix/state"
	path = strings.Replace(path, "{findingId}", url.PathEscape(in.FindingID), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	data, err := c.do(ctx, "GET", fullURL, nil)
	if err != nil {
		return nil, err
	}
	var out models.EndpointsGetCSPMFindingAutofixStateOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// ListCspmFindingsFindingIdAutofixStatusInput is the input for ListCspmFindingsFindingIdAutofixStatus — Get CSPM Finding Autofix Status.
type ListCspmFindingsFindingIdAutofixStatusInput struct {
	FindingID string `path:"findingId" json:"-"`
	models.RequestScope
}

// ListCspmFindingsFindingIdAutofixStatus - Get CSPM Finding Autofix Status
// GET /cspm/findings/{findingId}/autofix/status
func (c *Client) ListCspmFindingsFindingIdAutofixStatus(ctx context.Context, in ListCspmFindingsFindingIdAutofixStatusInput) (*models.EndpointsGetCSPMFindingAutofixStatusOutput, error) {
	path := "/cspm/findings/{findingId}/autofix/status"
	path = strings.Replace(path, "{findingId}", url.PathEscape(in.FindingID), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	data, err := c.do(ctx, "GET", fullURL, nil)
	if err != nil {
		return nil, err
	}
	var out models.EndpointsGetCSPMFindingAutofixStatusOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// CreateCspmFindingsFindingIdTicketInput is the input for CreateCspmFindingsFindingIdTicket — Create Ticket for CSPM Finding.
type CreateCspmFindingsFindingIdTicketInput struct {
	FindingID string `path:"findingId" json:"-"`
	Assignees []models.ModelsUser `json:"assignees,omitempty"`
	CampaignID *string `json:"campaignId,omitempty"`
	CampaignTitle *string `json:"campaignTitle,omitempty"`
	Message *string `json:"message,omitempty"`
	Project *string `json:"project,omitempty"`
	UserCanonicalID *string `json:"userCanonicalId,omitempty"`
	models.RequestScope
}

// CreateCspmFindingsFindingIdTicket - Create Ticket for CSPM Finding
// POST /cspm/findings/{findingId}/ticket
func (c *Client) CreateCspmFindingsFindingIdTicket(ctx context.Context, in CreateCspmFindingsFindingIdTicketInput) (*models.EndpointsPostCreateTicketCSPMFindingOutput, error) {
	path := "/cspm/findings/{findingId}/ticket"
	path = strings.Replace(path, "{findingId}", url.PathEscape(in.FindingID), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	bodyBytes, err := json.Marshal(struct {
		Assignees []models.ModelsUser `json:"assignees,omitempty"`
		CampaignID *string `json:"campaignId,omitempty"`
		CampaignTitle *string `json:"campaignTitle,omitempty"`
		Message *string `json:"message,omitempty"`
		Project *string `json:"project,omitempty"`
		UserCanonicalID *string `json:"userCanonicalId,omitempty"`
	}{
		Assignees: in.Assignees,
		CampaignID: in.CampaignID,
		CampaignTitle: in.CampaignTitle,
		Message: in.Message,
		Project: in.Project,
		UserCanonicalID: in.UserCanonicalID,
	})
	if err != nil {
		return nil, fmt.Errorf("marshal body: %w", err)
	}
	data, err := c.do(ctx, "POST", fullURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	var out models.EndpointsPostCreateTicketCSPMFindingOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// ListCspmScansInput is the input for ListCspmScans — Get CSPM Scans.
type ListCspmScansInput struct {
	AccountID *string `url:"accountId,omitempty" json:"-"`
	Limit *int `url:"limit,omitempty" json:"-"`
	NextToken *string `url:"nextToken,omitempty" json:"-"`
	Region *string `url:"region,omitempty" json:"-"`
	ScanType *string `url:"scanType,omitempty" json:"-"`
	Status *string `url:"status,omitempty" json:"-"`
	models.RequestScope
}

// ListCspmScans - Get CSPM Scans
// GET /cspm/scans
func (c *Client) ListCspmScans(ctx context.Context, in ListCspmScansInput) (*models.EndpointsGetCSPMScansOutput, error) {
	path := "/cspm/scans"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if in.Limit != nil {
		query.Set("limit", strconv.Itoa(int(*in.Limit)))
	}
	if in.NextToken != nil {
		query.Set("nextToken", string(*in.NextToken))
	}
	if in.Status != nil {
		query.Set("status", string(*in.Status))
	}
	if in.AccountID != nil {
		query.Set("accountId", string(*in.AccountID))
	}
	if in.Region != nil {
		query.Set("region", string(*in.Region))
	}
	if in.ScanType != nil {
		query.Set("scanType", string(*in.ScanType))
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	data, err := c.do(ctx, "GET", fullURL, nil)
	if err != nil {
		return nil, err
	}
	var out models.EndpointsGetCSPMScansOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

// GetCspmScansScanIdInput is the input for GetCspmScansScanId — Get CSPM Scan.
type GetCspmScansScanIdInput struct {
	ScanID string `path:"scanId" json:"-"`
	models.RequestScope
}

// GetCspmScansScanId - Get CSPM Scan
// GET /cspm/scans/{scanId}
func (c *Client) GetCspmScansScanId(ctx context.Context, in GetCspmScansScanIdInput) (*models.EndpointsGetCSPMScanOutput, error) {
	path := "/cspm/scans/{scanId}"
	path = strings.Replace(path, "{scanId}", url.PathEscape(in.ScanID), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	in.RequestScope.AddTo(query)

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	data, err := c.do(ctx, "GET", fullURL, nil)
	if err != nil {
		return nil, err
	}
	var out models.EndpointsGetCSPMScanOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &out, nil
}

