// Code generated by scripts/generate/main.go. DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/url"
)

// ListGraphAccounts - List Graph Account IDs
// GET /graph/accounts
func (c *Client) ListGraphAccounts(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/graph/accounts"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListGraphAll - Get All Graph Nodes and Relationships
// GET /graph/all
func (c *Client) ListGraphAll(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/graph/all"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListGraphDataLatest - Get Latest Graph Data
// GET /graph/data/latest
func (c *Client) ListGraphDataLatest(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/graph/data/latest"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListGraphNodes - Get Nodes by Type
// GET /graph/nodes
func (c *Client) ListGraphNodes(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/graph/nodes"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nodeType"); v != "" {
		query.Set("nodeType", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListGraphNodesSearch - Search Nodes
// GET /graph/nodes/search
func (c *Client) ListGraphNodesSearch(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/graph/nodes/search"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("query"); v != "" {
		query.Set("query", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}
