// Code generated by scripts/generate/main.go. DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"io"
	"net/url"
	"strings"
)

// CreateScpmContainersAnalyze - Request malware analysis for an OCI container image
// POST /scpm/containers/analyze
func (c *Client) CreateScpmContainersAnalyze(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/containers/analyze"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListScpmDependencies - Get CI/CD Dependencies
// GET /scpm/dependencies
func (c *Client) ListScpmDependencies(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/dependencies"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("name"); v != "" {
		query.Set("name", v)
	}
	if v := params.Get("version"); v != "" {
		query.Set("version", v)
	}
	if v := params.Get("platform"); v != "" {
		query.Set("platform", v)
	}
	if v := params.Get("pinned"); v != "" {
		query.Set("pinned", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateScpmDependenciesAnalyze - Request malware analysis for a dependency
// POST /scpm/dependencies/analyze
func (c *Client) CreateScpmDependenciesAnalyze(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/dependencies/analyze"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// CreateScpmDependenciesQueryBatch - Batch query vulnerabilities + malware verdict for dependencies
// POST /scpm/dependencies/query/batch
func (c *Client) CreateScpmDependenciesQueryBatch(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/dependencies/query/batch"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListScpmEvents - Get SCPM Events
// GET /scpm/events
func (c *Client) ListScpmEvents(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/events"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListScpmFindings - Get SCPM Findings
// GET /scpm/findings
func (c *Client) ListScpmFindings(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("priorityLabel"); v != "" {
		query.Set("priorityLabel", v)
	}
	if v := params.Get("severity"); v != "" {
		query.Set("severity", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("hasPullRequest"); v != "" {
		query.Set("hasPullRequest", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("workflow"); v != "" {
		query.Set("workflow", v)
	}
	if v := params.Get("repositoryIds"); v != "" {
		query.Set("repositoryIds", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isFixed"); v != "" {
		query.Set("isFixed", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isArchived"); v != "" {
		query.Set("isArchived", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateScpmFindingsAllowlist - Allowlist Batch of SCPM Findings
// POST /scpm/findings/allowlist
func (c *Client) CreateScpmFindingsAllowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/allowlist"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListScpmFindingsDetailed - Get Findings Detailed
// GET /scpm/findings/detailed
func (c *Client) ListScpmFindingsDetailed(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/detailed"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("priorityLabel"); v != "" {
		query.Set("priorityLabel", v)
	}
	if v := params.Get("severity"); v != "" {
		query.Set("severity", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("hasPullRequest"); v != "" {
		query.Set("hasPullRequest", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("workflow"); v != "" {
		query.Set("workflow", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isFixed"); v != "" {
		query.Set("isFixed", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isArchived"); v != "" {
		query.Set("isArchived", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListScpmFindingsPreview - Get SCPM Findings
// GET /scpm/findings/preview
func (c *Client) ListScpmFindingsPreview(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/preview"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("priorityLabel"); v != "" {
		query.Set("priorityLabel", v)
	}
	if v := params.Get("severity"); v != "" {
		query.Set("severity", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("hasPullRequest"); v != "" {
		query.Set("hasPullRequest", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("workflow"); v != "" {
		query.Set("workflow", v)
	}
	if v := params.Get("repositoryIds"); v != "" {
		query.Set("repositoryIds", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isFixed"); v != "" {
		query.Set("isFixed", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isArchived"); v != "" {
		query.Set("isArchived", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateScpmFindingsRetriage - Retriage Findings
// POST /scpm/findings/retriage
func (c *Client) CreateScpmFindingsRetriage(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/retriage"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// CreateScpmFindingsUpload - Get Presigned URL to Upload SCPM Findings
// POST /scpm/findings/upload
func (c *Client) CreateScpmFindingsUpload(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/upload"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// GetScpmFindingsFindingId - Get Finding
// GET /scpm/findings/{findingId}
func (c *Client) GetScpmFindingsFindingId(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// PatchScpmFindingsFindingId - Update Finding
// PATCH /scpm/findings/{findingId}
func (c *Client) PatchScpmFindingsFindingId(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "PATCH", fullURL, body)
}

// CreateScpmFindingsFindingIdAllowlist - Allowlist Finding
// POST /scpm/findings/{findingId}/allowlist
func (c *Client) CreateScpmFindingsFindingIdAllowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/{findingId}/allowlist"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListScpmFindingsFindingIdAutofixActivity - Get SCPM Finding Autofix Activity
// GET /scpm/findings/{findingId}/autofix/activity
func (c *Client) ListScpmFindingsFindingIdAutofixActivity(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/{findingId}/autofix/activity"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("since_id"); v != "" {
		query.Set("since_id", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateScpmFindingsFindingIdAutofixCache - Cache Autofix
// POST /scpm/findings/{findingId}/autofix/cache
func (c *Client) CreateScpmFindingsFindingIdAutofixCache(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/{findingId}/autofix/cache"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// CreateScpmFindingsFindingIdAutofixCacheCreatePr - Create Pull Request from Cached Fix
// POST /scpm/findings/{findingId}/autofix/cache/create_pr
func (c *Client) CreateScpmFindingsFindingIdAutofixCacheCreatePr(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/{findingId}/autofix/cache/create_pr"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListScpmFindingsFindingIdAutofixCacheDiff - Get SCPM Finding Autofix Diff
// GET /scpm/findings/{findingId}/autofix/cache/diff
func (c *Client) ListScpmFindingsFindingIdAutofixCacheDiff(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/{findingId}/autofix/cache/diff"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateScpmFindingsFindingIdAutofixFix - Autofix Finding
// POST /scpm/findings/{findingId}/autofix/fix
func (c *Client) CreateScpmFindingsFindingIdAutofixFix(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/{findingId}/autofix/fix"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListScpmFindingsFindingIdAutofixState - Get SCPM Finding Autofix State
// GET /scpm/findings/{findingId}/autofix/state
func (c *Client) ListScpmFindingsFindingIdAutofixState(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/{findingId}/autofix/state"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListScpmFindingsFindingIdAutofixStatus - Get SCPM Finding Autofix Status
// GET /scpm/findings/{findingId}/autofix/status
func (c *Client) ListScpmFindingsFindingIdAutofixStatus(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/{findingId}/autofix/status"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListScpmFindingsFindingIdEvents - Get Finding Events
// GET /scpm/findings/{findingId}/events
func (c *Client) ListScpmFindingsFindingIdEvents(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/{findingId}/events"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListScpmFindingsFindingIdTriage - Get Triaged Finding
// GET /scpm/findings/{findingId}/triage
func (c *Client) ListScpmFindingsFindingIdTriage(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/scpm/findings/{findingId}/triage"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateScpmFindingsFindingIdUnallowlist - Unallowlist Finding
// POST /scpm/findings/{findingId}/unallowlist
func (c *Client) CreateScpmFindingsFindingIdUnallowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/scpm/findings/{findingId}/unallowlist"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}
