// Code generated by scripts/generate/main.go. DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"io"
	"net/url"
	"strings"
)

// ListSecretsCredentialsFindings - Get Secrets Credential Findings
// GET /secrets/credentials/findings
func (c *Client) ListSecretsCredentialsFindings(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/credentials/findings"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("secretType"); v != "" {
		query.Set("secretType", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsCredentialsFindingsAllowlistBatch - Allowlist Batch of Credential Findings
// POST /secrets/credentials/findings/allowlist/batch
func (c *Client) CreateSecretsCredentialsFindingsAllowlistBatch(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/credentials/findings/allowlist/batch"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsCredentialsFindingsDetailed - Get Secrets Credential Findings Detailed
// GET /secrets/credentials/findings/detailed
func (c *Client) ListSecretsCredentialsFindingsDetailed(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/credentials/findings/detailed"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("secretType"); v != "" {
		query.Set("secretType", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// PatchSecretsCredentialsFindingsFindingId - Update Credential Finding
// PATCH /secrets/credentials/findings/{findingId}
func (c *Client) PatchSecretsCredentialsFindingsFindingId(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/credentials/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "PATCH", fullURL, body)
}

// GetSecretsCredentialsFindingsFindingId - Get Credential Finding
// GET /secrets/credentials/findings/{findingId}
func (c *Client) GetSecretsCredentialsFindingsFindingId(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/credentials/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsCredentialsFindingsFindingIdAllowlist - Allowlist Credential Finding
// POST /secrets/credentials/findings/{findingId}/allowlist
func (c *Client) CreateSecretsCredentialsFindingsFindingIdAllowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/credentials/findings/{findingId}/allowlist"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsCredentialsFindingsFindingIdEvents - Get Finding Events
// GET /secrets/credentials/findings/{findingId}/events
func (c *Client) ListSecretsCredentialsFindingsFindingIdEvents(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/credentials/findings/{findingId}/events"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsCredentialsFindingsFindingIdTicket - Create Ticket for Credential Finding
// POST /secrets/credentials/findings/{findingId}/ticket
func (c *Client) CreateSecretsCredentialsFindingsFindingIdTicket(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/credentials/findings/{findingId}/ticket"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsCredentialsFindingsFindingIdTriage - Get Triaged Credential Finding
// GET /secrets/credentials/findings/{findingId}/triage
func (c *Client) ListSecretsCredentialsFindingsFindingIdTriage(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/credentials/findings/{findingId}/triage"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsCredentialsFindingsFindingIdUnallowlist - Unallowlist Credential Finding
// POST /secrets/credentials/findings/{findingId}/unallowlist
func (c *Client) CreateSecretsCredentialsFindingsFindingIdUnallowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/credentials/findings/{findingId}/unallowlist"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsCredentialsFindingsFindingIdUsers - Get Credential Finding Related Users
// GET /secrets/credentials/findings/{findingId}/users
func (c *Client) ListSecretsCredentialsFindingsFindingIdUsers(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/credentials/findings/{findingId}/users"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListSecretsEvents - Get Secret Events
// GET /secrets/events
func (c *Client) ListSecretsEvents(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/events"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("fromTime"); v != "" {
		query.Set("fromTime", v)
	}
	if v := params.Get("numItems"); v != "" {
		query.Set("numItems", v)
	}
	if v := params.Get("eventType"); v != "" {
		query.Set("eventType", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListSecretsFindings - Get Secrets Credential Findings
// GET /secrets/findings
func (c *Client) ListSecretsFindings(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/findings"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("secretType"); v != "" {
		query.Set("secretType", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsFindingsAllowlistBatch - Allowlist Batch of Credential Findings
// POST /secrets/findings/allowlist/batch
func (c *Client) CreateSecretsFindingsAllowlistBatch(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/findings/allowlist/batch"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsFindingsDetailed - Get Secrets Credential Findings Detailed - [DEPRECATED - TO BE REMOVED BY 2025]
// GET /secrets/findings/detailed
func (c *Client) ListSecretsFindingsDetailed(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/findings/detailed"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("secretType"); v != "" {
		query.Set("secretType", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListSecretsFindingsPreview - Get Secrets Credential Findings
// GET /secrets/findings/preview
func (c *Client) ListSecretsFindingsPreview(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/findings/preview"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("secretType"); v != "" {
		query.Set("secretType", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// PatchSecretsFindingsFindingId - Update Credential Finding
// PATCH /secrets/findings/{findingId}
func (c *Client) PatchSecretsFindingsFindingId(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "PATCH", fullURL, body)
}

// GetSecretsFindingsFindingId - Get Credential Finding
// GET /secrets/findings/{findingId}
func (c *Client) GetSecretsFindingsFindingId(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsFindingsFindingIdAllowlist - Allowlist Credential Finding
// POST /secrets/findings/{findingId}/allowlist
func (c *Client) CreateSecretsFindingsFindingIdAllowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/findings/{findingId}/allowlist"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsFindingsFindingIdEvents - Get Finding Events
// GET /secrets/findings/{findingId}/events
func (c *Client) ListSecretsFindingsFindingIdEvents(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/findings/{findingId}/events"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsFindingsFindingIdTicket - Create Ticket for Credential Finding
// POST /secrets/findings/{findingId}/ticket
func (c *Client) CreateSecretsFindingsFindingIdTicket(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/findings/{findingId}/ticket"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsFindingsFindingIdTriage - Get Triaged Credential Finding
// GET /secrets/findings/{findingId}/triage
func (c *Client) ListSecretsFindingsFindingIdTriage(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/findings/{findingId}/triage"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsFindingsFindingIdUnallowlist - Unallowlist Credential Finding
// POST /secrets/findings/{findingId}/unallowlist
func (c *Client) CreateSecretsFindingsFindingIdUnallowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/findings/{findingId}/unallowlist"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsFindingsFindingIdUsers - Get Credential Finding Related Users
// GET /secrets/findings/{findingId}/users
func (c *Client) ListSecretsFindingsFindingIdUsers(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/findings/{findingId}/users"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// ListSecretsSensitivedataFindings - Get Sensitive Data Findings
// GET /secrets/sensitivedata/findings
func (c *Client) ListSecretsSensitivedataFindings(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/sensitivedata/findings"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("nextToken"); v != "" {
		query.Set("nextToken", v)
	}
	if v := params.Get("limit"); v != "" {
		query.Set("limit", v)
	}
	if v := params.Get("branch"); v != "" {
		query.Set("branch", v)
	}
	if v := params.Get("secretType"); v != "" {
		query.Set("secretType", v)
	}
	if v := params.Get("fileOwnerName"); v != "" {
		query.Set("fileOwnerName", v)
	}
	if v := params.Get("isResolved"); v != "" {
		query.Set("isResolved", v)
	}
	if v := params.Get("isAllowlisted"); v != "" {
		query.Set("isAllowlisted", v)
	}
	if v := params.Get("isFalsePositive"); v != "" {
		query.Set("isFalsePositive", v)
	}
	if v := params.Get("sortBy"); v != "" {
		query.Set("sortBy", v)
	}
	if v := params.Get("sort"); v != "" {
		query.Set("sort", v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsSensitivedataFindingsAllowlistBatch - Allowlist Batch of Sensitive Data Findings
// POST /secrets/sensitivedata/findings/allowlist/batch
func (c *Client) CreateSecretsSensitivedataFindingsAllowlistBatch(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/sensitivedata/findings/allowlist/batch"

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// PatchSecretsSensitivedataFindingsFindingId - Update Sensitive Data Finding
// PATCH /secrets/sensitivedata/findings/{findingId}
func (c *Client) PatchSecretsSensitivedataFindingsFindingId(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/sensitivedata/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "PATCH", fullURL, body)
}

// GetSecretsSensitivedataFindingsFindingId - Get Sensitive Data Finding
// GET /secrets/sensitivedata/findings/{findingId}
func (c *Client) GetSecretsSensitivedataFindingsFindingId(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/sensitivedata/findings/{findingId}"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsSensitivedataFindingsFindingIdAllowlist - Allowlist Sensitive Data Finding
// POST /secrets/sensitivedata/findings/{findingId}/allowlist
func (c *Client) CreateSecretsSensitivedataFindingsFindingIdAllowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/sensitivedata/findings/{findingId}/allowlist"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// CreateSecretsSensitivedataFindingsFindingIdTicket - Create Ticket for Sensitive Data Finding
// POST /secrets/sensitivedata/findings/{findingId}/ticket
func (c *Client) CreateSecretsSensitivedataFindingsFindingIdTicket(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/sensitivedata/findings/{findingId}/ticket"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsSensitivedataFindingsFindingIdTriage - Get Triaged Sensitive Data Finding
// GET /secrets/sensitivedata/findings/{findingId}/triage
func (c *Client) ListSecretsSensitivedataFindingsFindingIdTriage(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/sensitivedata/findings/{findingId}/triage"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}

// CreateSecretsSensitivedataFindingsFindingIdUnallowlist - Unallowlist Sensitive Data Finding
// POST /secrets/sensitivedata/findings/{findingId}/unallowlist
func (c *Client) CreateSecretsSensitivedataFindingsFindingIdUnallowlist(ctx context.Context, params url.Values, body io.Reader) ([]byte, error) {
	path := "/secrets/sensitivedata/findings/{findingId}/unallowlist"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "POST", fullURL, body)
}

// ListSecretsSensitivedataFindingsFindingIdUsers - Get Sensitive Data Finding Related Users
// GET /secrets/sensitivedata/findings/{findingId}/users
func (c *Client) ListSecretsSensitivedataFindingsFindingIdUsers(ctx context.Context, params url.Values) ([]byte, error) {
	path := "/secrets/sensitivedata/findings/{findingId}/users"
	path = strings.Replace(path, "{findingId}", params.Get("findingId"), 1)

	query := url.Values{}
	for k, v := range c.DefaultParams {
		query.Set(k, v)
	}
	if v := params.Get("azureOrganizationId"); v != "" {
		query.Set("azureOrganizationId", v)
	}
	if v := params.Get("bitbucketWorkspaceId"); v != "" {
		query.Set("bitbucketWorkspaceId", v)
	}
	if v := params.Get("githubOwnerId"); v != "" {
		query.Set("githubOwnerId", v)
	}
	if v := params.Get("gitlabGroupId"); v != "" {
		query.Set("gitlabGroupId", v)
	}
	if v := params.Get("installationId"); v != "" {
		query.Set("installationId", v)
	}
	if v := params.Get("azureRepositoryId"); v != "" {
		query.Set("azureRepositoryId", v)
	}
	if v := params.Get("githubRepositoryId"); v != "" {
		query.Set("githubRepositoryId", v)
	}
	if v := params.Get("githubTeamId"); v != "" {
		query.Set("githubTeamId", v)
	}
	if v := params.Get("bitbucketRepositoryId"); v != "" {
		query.Set("bitbucketRepositoryId", v)
	}

	fullURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	return c.do(ctx, "GET", fullURL, nil)
}
